### ISSUE TITLE
After winning a game, the rank or stars are not always updated

### ISSUE THREAD

**Issue by HearthstoneBugs** [HearthSim/hs-bugs#261]
This is a random bug so not easy to reproduce - sometimes after winning a game the rank display will not change or, in cases where a star (or two) should be added, the new star(s) isn't displayed. The new rank/star is though correctly displayed in the Play screen and Quest Log. Also affected are Quests - if a Quest has just been successfully completed and it coincides with the lack of rank/star update then the Quest completion and award will not be displayed until the game is restarted.

**Comment by jleclanche** [comment]
Do you have a power.log of this happening?

**Comment by HearthstoneBugs** [comment]
Afraid not, but I've just enabled it so I'll report back here with the relevant data when the bug occurs again.

I've also seen a couple of people mention it on the Hearthstone reddit.

**Comment by jleclanche** [comment]
I'm specifically interested in the last ~300 lines when a game ends.

**Comment by HearthstoneBugs** [comment]
Okay. 300 lines is a lot though, do I just post them all in a comment in this thread?

**Comment by jleclanche** [comment]
gist.github.com

**Comment by HearthstoneBugs** [comment]
I've just had an instance of this bug and have now created a file with the relevant lines of the power.log, here it is:

https://gist.github.com/HearthstoneBugs/4bba69e4bbfa4a008527

Just for privacy I've edited the log and changed my opponent's name to "opponent" and my name to "HearthstoneBugs".

**Comment by PattuX** [comment]
Appearently this can make it happen that the animation for your 500th ranked win with a class is delayed for one game.

https://youtu.be/wIcQ8S_5N4k?t=26m25s

At 12:12  You can see how he is at 499/500 wins and 4 stars, then loses one star and after his next win the animation for the regained 4th star is missing, When he goes back to main menu it appears correctly.

The animation for the 500th win is missing aswell but - unlike the star - it doesn't show up correctly in main menu as the counter stays at 499/500 wins. In the very next game he has obtained golden Druid nonetheless and gets the animation for that after the win.



Also I want to mention that this (or a similar) bug sometimes occurs when closing Hearthstone or disconnecting and not get back in time. Then the lost star is not displayed correctly in the Play screen (didn't check Quest Log when it happened yet) but only updated after the next game, where you either lose two stars at once or nothing changes in the After game screen.

**Comment by culinko** [comment]
Still present in current patch: https://www.reddit.com/r/hearthstone/comments/3vkh92/bug_concedes_dont_count_wins_towards_quests/.

**Comment by PattuX** [comment]
According to iPad Patch notes this should be fixed in 4.1

**Comment by culinko** [comment]
I don't think this should have the mobile tag, since it happened to Noxious on PC and I've seen it on multiple other streams myself.

**Comment by PattuX** [comment]
That's also not what I meant with my comment. Just wanted to let you know it is mentioned in iOS Patch but not in PC patch for some reason.
I wouldn't be too sure whether the reddit comments are from 4.1 btw.

**Comment by HearthstoneBugs** [comment]
It's definitely not fixed on the PC. Happened to me a few times yesterday.

**Comment by culinko** [comment]
Happened to me yesterday with a golden Fire Elemental for my shaman lvl 50. I had the card awarded only after my next game.

**Comment by PattuX** [comment]
Can also happen in brawl: https://youtu.be/Dp_pFR_s1qg?t=4m47s

Your win count does not go up and you don't recieve your free pack.

Also Xinhuan noted, that all occurences happened after wins due to opponents conceding.

**Comment by culinko** [comment]
Another report: https://www.reddit.com/r/hearthstone/comments/46ku85/the_ladder_progression_bug_visual/.

**Comment by Patashu** [comment]
Confirmed in 4.2

http://us.battle.net/hearthstone/en/forum/topic/20742935879

**Comment by Patashu** [comment]
http://us.battle.net/hearthstone/en/forum/topic/20746924734 maybe confirmed in 5.2.0?

**Comment by Patashu** [comment]
Confirmed in 7.0? Kripp's 'Priest Mastery' quest is awarded about a minute after he finished it.

https://clips.twitch.tv/nl_kripp/ThankfulAntKappaRoss

**Comment by troggnostupidhs** [comment]
That instance occurred when Blizzard's servers were having connection issues

https://www.youtube.com/watch?v=FMxITJkY-8s
Skip Kripp at 2:00
Clip for the delay award starts from 5:15

**Comment by Patashu** [comment]
Ok - but is the cause of the bug only ever due to Blizzard's servers having connection issues or is it also a client bug that happens randomly?

**Comment by jleclanche** [comment]
Yeah I mean, none of this is really useful. If it's just the servers being slow at processing events because they're under stress we shouldn't be tracking this.

**Comment by culinko** [comment]
I agree that if it's just server issues (caching?) it shouldn't be tracked, but figuring out if whether it's the case might be impossible.

**Comment by troggnostupidhs** [comment]
That's why I wanted to note it this time. I'm not sure what the situation was for the previous cases, but going forward we can see if it only happens when the servers are having connection issues.
