### ISSUE TITLE
Shadow Madness and Power Overwhelming is inconsistent (Dominant Player Bug)

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#62]
If you use Shadow Madness then Power Overwhelming on a minion, the result at the end of your turn depends on whether you are the Dominant Player (your PLAYER_ID is 1) or the Secondary Player (your PLAYER_ID is 2).

If you are the Dominant Player, the minion is returned to your opponent, then triggers and dies.

If you are the Secondary Player, the minion is returned to your opponent but does not die. When he ends his turn, it finally dies for him.

[[Hearthstone Science] The Dominant Player Bug (Shadow Madness+Power Overwhelming and more)](https://www.youtube.com/watch?v=iWftn94D1Sc)

Note that if Sylvanas Windrunner steals your minion with the Power Overwhelming bug, when you end your turn, the minion dies as expected.

* http://us.battle.net/hearthstone/en/forum/topic/17084749125
* https://www.reddit.com/r/hearthstone/comments/43ckti/shadow_madness_power_overwhelming/

**Comment by Patashu** [comment]
This is a side-effect of the Dominant Player Bug: https://github.com/HearthSim/hs-bugs/issues/29

**Comment by Patashu** [comment]
Got a report of this in 3.0

http://us.battle.net/hearthstone/en/forum/topic/18716987354

**Comment by Xinhuan** [comment]
Verified Shadow Madness + Power Overwhelming with Patashu. Still occurs today.

**Comment by Patashu** [comment]
Confirmed in 4.0 video

https://www.youtube.com/watch?v=58elEoHyeSY

**Comment by 10925** [comment]
https://www.youtube.com/watch?v=5WQQSCauLcE&feature=youtu.be
Seems like it got fixed in patch 5.0(Although other "Dominant Player Bug"  like #20 still works)
Still wondering how they fixed it……

**Comment by Kybxd** [comment]
https://youtu.be/guWGi33UYLU

**Comment by Patashu** [comment]
@Kybxd: So my understanding was that ALL triggers become invalidated when they are stolen after their trigger has been queued. If they can still queue for the other player, they'll queue if the queue is later (e.g. stolen from dominant -> secondary) and not if it is too late. It's not a condition on any particular trigger, just a rule of how Hearthstone works.

So has this general rule been changed, perhaps? Can you also re-test https://www.youtube.com/watch?v=4BEPttjTTRA and https://www.youtube.com/watch?v=pZvyhb3GzVI please?

**Comment by Kybxd** [comment]
The Flesheating Ghoul stolen by Dominant Player's Sylvanas is still unable to trigger. https://youtu.be/goGF1ofoxkA (I'm the Dominant Player.)

I've also tested this:Dominant Player's Power Overwhelming minion is stolen by Sylvanas,then he plays an Echoing Ooze.However,at the end of his turn,Power Overwhelming still triggers earlier than Echoing Ooze.(It should have been resolved in Secondary Player's queue,later than ooze.)
https://youtu.be/F8P4W5abbcM (I'm the Dominant Player.)

**Comment by Patashu** [comment]
> I've also tested this:Dominant Player's Power Overwhelming minion is stolen by Sylvanas,then he plays an Echoing Ooze.However,at the end of his turn,Power Overwhelming still triggers earlier than Echoing Ooze.(It should have been resolved in Secondary Player's queue,later than ooze.)

Do you have logging enabled? This might be caused by the CONTROLLER tag of attached Enchantments no longer being changed when the minion they are attached to's CONTROLLER tag change. This will cause the following interactions to change, listed here:

http://hearthstone.gamepedia.com/Advanced_rulebook#Controllers_of_Enchantments_and_Minions

And it also means that the Dominant Player Bug has not changed at all - rather, since attached Enchantments don't ever change controllers, they are not being invalidated to begin with.

**Comment by Kybxd** [comment]
>The CONTROLLER tag of attached Enchantments no longer being changed when the minion they are attached to's CONTROLLER tag change. 

I repeated the Auchenai vs Glory test and found that your idea was correct:
https://youtu.be/XdA_xw_Ei1M

**Comment by Patashu** [comment]
Thanks for your help! I'll update the Advanced rulebook later.

**Comment by troggnostupidhs** [comment]
#821 

Should this be retested?
